aws:
  s3:
    bucket-name: vova
    region: ru-central-1
    access-key: "40c9d70a-513a-4f44-b101-2482e4eda4c0:c6cd2ea5d09a42f85f1291ab9e11069a"
    secret-key: "123456s"
    endpoint-url: https://s3.cloud.ru/