security:
  jwt:
    token:
      secret-key: "your_very_long_and_very_secure_secret_key_that_is_at_least_256_bits_long_please_change_this_in_production_environment_and_store_securely_12345678901234567890"
      expire-length: 3600000

server:
  port: 8081  # или любой другой порт

recommendation-service:
  url: http://localhost:8085


spring:
  config:
    import: "optional:classpath:/application-secrets.yml"
  profiles:
    active: dev  
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**