
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spoopify
    username: greh
    password: isohateis
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

recommendation-service:
  url: http://localhost:8085